#!/usr/bin/env python3# -*- coding: utf-8 -*-

# This file is automatically generated on the fly by sim.py! Do not try to modify it please.

m_Alcar = 0
m_Carni = 1
m_Carno = 2
m_Cr_CH3 = 3
m_Cr_CH2 = 4
m_Eth = 5
m_Lac = 6
m_PCr = 7
m_Water = 8
m_LipA = 9
m_LipB = 10
m_LipC = 11
m_LipD = 12
m_LipE = 13
m_LipF = 14

p_cm = 0
p_dd = 1
p_df = 2
p_dp = 3

m_All_MBs = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, ]
m_Ref_MB = 3

m_All_MMs = []
m_Ref_MM = None

n_All = 15
n_MBs = 15
n_MMs = 0

