#!/usr/bin/env python3# -*- coding: utf-8 -*-

# This file is automatically generated on the fly by sim.py!

m_Ala = 0
m_Alcar = 1
m_Asc = 2
m_Asp = 3
m_Carni = 4
m_Carno = 5
m_Cho_CH3 = 6
m_Cho_CH2 = 7
m_Cr_CH3 = 8
m_Cr_CH2 = 9
m_EA = 10
m_Eth = 11
m_GABA = 12
m_Glc = 13
m_Gln = 14
m_Glu = 15
m_Gly = 16
m_GPC = 17
m_Gsh = 18
m_Lac = 19
m_mI = 20
m_NAA_CH3 = 21
m_NAA_CH2 = 22
m_NAAG = 23
m_PCr = 24
m_PC = 25
m_PE = 26
m_sI = 27
m_Tau = 28
m_Water = 29
m_MM1 = 30
m_MM2 = 31
m_MM3 = 32
m_MM4 = 33
m_Lip1 = 34
m_Lip2 = 35
m_Lip3 = 36
m_Lip4 = 37
m_Lip5 = 38

p_cm = 0
p_dd = 1
p_df = 2
p_dp = 3

m_All_MBs = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
m_All_MMs = [30, 31, 32, 33, 34, 35, 36, 37, 38]

n_ALL = 39
n_MBs = 30
n_MMs = 9

